[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@src/=src/"]

[fmt]
line_length = 80

[lint]
exclude_lints = [
    "screaming-snake-case-const",
    "screaming-snake-case-immutable",
    "unwrapped-modifier-logic"
]
